export const FONT_NAMES = {
  'inter':        'Inter',
  'roboto':       'Roboto',
  'open-sans':    'Open Sans',
  'nunito':       'Nunito',
  'lato':         'Lato',
  'merriweather': 'Merriweather',
  'lora':         'Lora',
  'playfair':     'Playfair Display',
  'crimson':      'Crimson Text',
  'source-code':  'Source Code Pro',
}

export const THEME_NAMES = {
  'basic':          'Basic',
  'pink':           'Pink',
  'purple':         'Purple',
  'mint':           'Mint green',
  'turquoise':      'Turquoise',
  'bw':             'Black & white',
  'sunset':         'Sunset',
  'forest':         'Forest',
  'sand':           'Sand',
  'dark':           'Dark',
  'darkred':        'Dark red',
  'darkviolet':     'Dark violet',
  'darkneon':       'Neon green',
  'darkneonblue':   'Neon blue',
  'darkneonred':    'Neon red',
  'darkneonyellow': 'Neon yellow',
  'darkneonpink':   'Neon pink',
  'darkneonorange': 'Neon orange',
  'caramel':        'Caramel',
  'ocean':          'Ocean',
  'midnight':       'Midnight',
  'cherry':         'Cherry',
}

export const FONT_VALUES = {
  'inter':        "'Inter', system-ui, sans-serif",
  'roboto':       "'Roboto', sans-serif",
  'open-sans':    "'Open Sans', sans-serif",
  'nunito':       "'Nunito', sans-serif",
  'lato':         "'Lato', sans-serif",
  'merriweather': "'Merriweather', serif",
  'lora':         "'Lora', serif",
  'playfair':     "'Playfair Display', serif",
  'crimson':      "'Crimson Text', serif",
  'source-code':  "'Source Code Pro', monospace",
}
